server.port: 8080
spring:
    datasource:
        url: jdbc:mysql://66.70.137.253:3306/Javeriana
        username: javeriana
        password: 87654321
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                format_sql: true
        database: mysql